create database Direct_Backend_DB;
use Direct_Backend_DB;

DROP TABLE IF EXISTS USER_ACCOUNT;
CREATE TABLE USER_ACCOUNT (
    USER_ACCOUNT_USERNAME CHAR(20) NOT NULL UNIQUE,
    USER_ACCOUNT_PASSWORD CHAR(32) NOT NULL,
    USER_ACCOUNT_ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PRIMARY KEY (USER_ACCOUNT_ID)
);
INSERT INTO USER_ACCOUNT (USER_ACCOUNT_USERNAME, USER_ACCOUNT_PASSWORD)
VALUES 
('user1', 'password1'),
('user2', 'password2');