create database Direct_Backend_DB;
use Direct_Backend_DB;

CREATE TABLE USER_ACC (
    USER_ACC_ID INT AUTO_INCREMENT,
    USER_ACC_USERNAME CHAR(64),
    USER_ACC_PASSWORD CHAR(64),
    USER_ACC_NAME CHAR(64),
    USER_ACC_IS_DEL BIT,
    PRIMARY KEY (USER_ACC_ID)
);

CREATE TABLE USER_OPK_KEY (
    USER_OPK_KEY_ID INT,
    USER_ACC_ID INT,
    USER_OPK_KEY BINARY(32),
    USER_OPK_KEY_IS_DEL BIT,
    PRIMARY KEY (USER_ACC_ID , USER_OPK_KEY_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE USER_TOKEN (
    USER_TOKEN CHAR(64),
    USER_ACC_ID INT,
    USER_TOKEN_TIMEOUT DATETIME,
    USER_TOKEN_IS_DEL BIT,
    PRIMARY KEY (USER_TOKEN , USER_ACC_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE USER_FRIEND (
    USER_ACC_ID_1 INT,
    USER_ACC_ID_2 INT,
    USER_FRIEND_IS_DEL BIT,
    USER_FRIEND_SINCE DATETIME,
    PRIMARY KEY (USER_ACC_ID_1 , USER_ACC_ID_2),
    FOREIGN KEY (USER_ACC_ID_1)
        REFERENCES USER_ACC (USER_ACC_ID),
    FOREIGN KEY (USER_ACC_ID_2)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE USER_KEY (
    USER_ACC_ID INT,
    USER_KEY_ID_DEL BIT,
    USER_KEY_IK BINARY(32),
    USER_KEY_SPK BINARY(32),
    PRIMARY KEY (USER_ACC_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE USER_GROUP (
    USER_GROUP_ID INT AUTO_INCREMENT UNIQUE,
    USER_ACC_ID INT,
    USER_GROUP_SINCE DATETIME,
    PRIMARY KEY (USER_GROUP_ID, USER_ACC_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE GROUP_LINKER (
    USER_ACC_ID INT,
    USER_GROUP_ID INT,
    GROUP_LINKER_IS_DEL BIT,
    GROUP_LINKER_SINCE DATETIME,
    PRIMARY KEY (USER_ACC_ID , USER_GROUP_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID),
    FOREIGN KEY (USER_GROUP_ID)
        REFERENCES USER_GROUP (USER_GROUP_ID)
);

CREATE TABLE MESSAGE (
    USER_GROUP_ID INT,
    USER_ACC_ID INT,
    MESSAGE_CONTENT VARBINARY(1024),
    MESSAGE_SINCE DATETIME,
    PRIMARY KEY (USER_GROUP_ID, USER_ACC_ID, MESSAGE_SINCE),
    FOREIGN KEY (USER_GROUP_ID)
        REFERENCES USER_GROUP (USER_GROUP_ID),
    FOREIGN KEY (USER_ACC_ID)
        REFERENCES USER_ACC (USER_ACC_ID)
);

CREATE TABLE USER_FRIEND_REQUEST (
    USER_ACC_ID_FROM INT,
    USER_ACC_ID_TO INT,
    USER_FRIEND_REQUEST_EK VARCHAR(255),
    PRIMARY KEY (USER_ACC_ID_FROM , USER_ACC_ID_TO),
    FOREIGN KEY (USER_ACC_ID_FROM)
        REFERENCES USER_ACC (USER_ACC_ID),
    FOREIGN KEY (USER_ACC_ID_TO)
        REFERENCES USER_ACC (USER_ACC_ID)
);
